# Generated by Django 5.2 on 2025-04-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentevent_student_studentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
