# Generated by Django 5.2 on 2025-04-12 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentschedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
            preserve_default=False,
        ),
    ]
