# Generated by Django 5.2 on 2025-04-12 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studentschedule_date_studentschedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
