# Generated by Django 5.2 on 2025-04-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teachermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermessage',
            old_name='timestamp',
            new_name='sent_at',
        ),
    ]
