# Generated by Django 5.2 on 2025-05-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_assignment_course_and_more'),
    ]

    operations = [
    ]
