# Generated by Django 5.2 on 2025-05-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_student_docker_knowledge_and_more'),
    ]

    operations = [
    ]
