# Generated by Django 5.2 on 2025-05-21 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_force_lesson_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='assignment_due_date',
            new_name='available_until',
        ),
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='external_link',
            new_name='link_url',
        ),
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='assignment_instructions',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='sectioncontent',
            name='text_content',
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'External Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('homework', 'Homework'), ('lecture', 'Lecture'), ('summary', 'Summary')], max_length=20)),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
