# Generated by Django 5.2 on 2025-05-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_assignment_due_date_sectioncontent_available_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='available_until',
            new_name='assignment_due_date',
        ),
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='text',
            new_name='assignment_instructions',
        ),
        migrations.RenameField(
            model_name='sectioncontent',
            old_name='link_url',
            new_name='external_link',
        ),
        migrations.RemoveField(
            model_name='sectioncontent',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='student',
            name='docker_knowledge',
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_contents/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('video', 'Video'), ('audio', 'Audio'), ('assignment', 'Assignment'), ('link', 'External Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_contents/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='learning_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.learninglevel'),
        ),
        migrations.CreateModel(
            name='TimelineUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='timelines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
