# Generated by Django 5.2 on 2025-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_available_until_sectioncontent_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
