# Generated by Django 5.2 on 2025-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to='staticfiles/users/submissions/%Y/%m/%d/'),
        ),
    ]
