# Generated by Django 5.2 on 2025-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_submission_submitted_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_types',
            field=models.CharField(choices=[('file', 'File'), ('text', 'Text'), ('both', 'File or Text')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Submitted Late'), ('graded', 'Graded')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
