# Generated by Django 5.2 on 2025-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to='users/submissions/%Y/%m/%d/'),
        ),
    ]
