# Generated by Django 4.1.5 on 2025-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Submitted Late'), ('graded', 'Graded')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
